# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scatter_form.ui'
#
# Created: Mon Jan 09 21:14:20 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(256, 291)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.surface_name_dpy = QtGui.QLineEdit(self.centralwidget)
        self.surface_name_dpy.setEnabled(True)
        self.surface_name_dpy.setReadOnly(True)
        self.surface_name_dpy.setObjectName("surface_name_dpy")
        self.horizontalLayout_6.addWidget(self.surface_name_dpy)
        self.load_surface_btn = QtGui.QPushButton(self.centralwidget)
        self.load_surface_btn.setObjectName("load_surface_btn")
        self.horizontalLayout_6.addWidget(self.load_surface_btn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.object_name_dpy = QtGui.QLineEdit(self.centralwidget)
        self.object_name_dpy.setReadOnly(True)
        self.object_name_dpy.setObjectName("object_name_dpy")
        self.horizontalLayout_5.addWidget(self.object_name_dpy)
        self.load_object_btn = QtGui.QPushButton(self.centralwidget)
        self.load_object_btn.setObjectName("load_object_btn")
        self.horizontalLayout_5.addWidget(self.load_object_btn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.scatter_method_cmb = QtGui.QComboBox(self.centralwidget)
        self.scatter_method_cmb.setObjectName("scatter_method_cmb")
        self.scatter_method_cmb.addItem("")
        self.scatter_method_cmb.addItem("")
        self.horizontalLayout_4.addWidget(self.scatter_method_cmb)
        spacerItem2 = QtGui.QSpacerItem(60, 19, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.copy_type_cmb = QtGui.QComboBox(self.centralwidget)
        self.copy_type_cmb.setObjectName("copy_type_cmb")
        self.copy_type_cmb.addItem("")
        self.copy_type_cmb.addItem("")
        self.horizontalLayout_2.addWidget(self.copy_type_cmb)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.num_copies_spn = QtGui.QSpinBox(self.centralwidget)
        self.num_copies_spn.setMinimumSize(QtCore.QSize(100, 0))
        self.num_copies_spn.setMaximum(999999)
        self.num_copies_spn.setProperty("value", 10)
        self.num_copies_spn.setObjectName("num_copies_spn")
        self.horizontalLayout_3.addWidget(self.num_copies_spn)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.min_scale_spn = QtGui.QDoubleSpinBox(self.centralwidget)
        self.min_scale_spn.setSingleStep(0.25)
        self.min_scale_spn.setProperty("value", 1.0)
        self.min_scale_spn.setObjectName("min_scale_spn")
        self.horizontalLayout.addWidget(self.min_scale_spn)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.max_scale_spn = QtGui.QDoubleSpinBox(self.centralwidget)
        self.max_scale_spn.setSingleStep(0.25)
        self.max_scale_spn.setProperty("value", 1.0)
        self.max_scale_spn.setObjectName("max_scale_spn")
        self.horizontalLayout.addWidget(self.max_scale_spn)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.min_hue_spn = QtGui.QSpinBox(self.centralwidget)
        self.min_hue_spn.setObjectName("min_hue_spn")
        self.horizontalLayout_7.addWidget(self.min_hue_spn)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.max_hue_spn = QtGui.QSpinBox(self.centralwidget)
        self.max_hue_spn.setMaximum(31)
        self.max_hue_spn.setProperty("value", 31)
        self.max_hue_spn.setObjectName("max_hue_spn")
        self.horizontalLayout_7.addWidget(self.max_hue_spn)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.do_scatter_btn = QtGui.QPushButton(self.centralwidget)
        self.do_scatter_btn.setObjectName("do_scatter_btn")
        self.verticalLayout.addWidget(self.do_scatter_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 256, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ScatterTool", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.surface_name_dpy.setText(QtGui.QApplication.translate("MainWindow", "select surface...", None, QtGui.QApplication.UnicodeUTF8))
        self.load_surface_btn.setText(QtGui.QApplication.translate("MainWindow", "Load Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Object", None, QtGui.QApplication.UnicodeUTF8))
        self.object_name_dpy.setText(QtGui.QApplication.translate("MainWindow", "select object...", None, QtGui.QApplication.UnicodeUTF8))
        self.load_object_btn.setText(QtGui.QApplication.translate("MainWindow", "Load Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Scatter Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.scatter_method_cmb.setItemText(0, QtGui.QApplication.translate("MainWindow", "Faces", None, QtGui.QApplication.UnicodeUTF8))
        self.scatter_method_cmb.setItemText(1, QtGui.QApplication.translate("MainWindow", "Area/Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Copy Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.copy_type_cmb.setItemText(0, QtGui.QApplication.translate("MainWindow", "Instance", None, QtGui.QApplication.UnicodeUTF8))
        self.copy_type_cmb.setItemText(1, QtGui.QApplication.translate("MainWindow", "Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Number of Copies", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Min Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Max Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Min ColorIndex", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Max ColorIndex", None, QtGui.QApplication.UnicodeUTF8))
        self.do_scatter_btn.setText(QtGui.QApplication.translate("MainWindow", "Scatter", None, QtGui.QApplication.UnicodeUTF8))

